# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 454)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.greet_text = QtWidgets.QLabel(self.centralwidget)
        self.greet_text.setGeometry(QtCore.QRect(0, 0, 451, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.greet_text.setFont(font)
        self.greet_text.setObjectName("greet_text")
        self.graph = PlotWidget(self.centralwidget)
        self.graph.setGeometry(QtCore.QRect(495, 10, 291, 192))
        self.graph.setObjectName("graph")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(20, 360, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.var_text = QtWidgets.QLabel(self.centralwidget)
        self.var_text.setGeometry(QtCore.QRect(20, 180, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.var_text.setFont(font)
        self.var_text.setObjectName("var_text")
        self.equal_text = QtWidgets.QLabel(self.centralwidget)
        self.equal_text.setGeometry(QtCore.QRect(20, 130, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.equal_text.setFont(font)
        self.equal_text.setObjectName("equal_text")
        self.inf_text = QtWidgets.QLabel(self.centralwidget)
        self.inf_text.setGeometry(QtCore.QRect(500, 210, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.inf_text.setFont(font)
        self.inf_text.setObjectName("inf_text")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 451, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.y_const = QtWidgets.QRadioButton(self.layoutWidget)
        self.y_const.setObjectName("y_const")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.y_const)
        self.horizontalLayout.addWidget(self.y_const)
        self.y_kx = QtWidgets.QRadioButton(self.layoutWidget)
        self.y_kx.setObjectName("y_kx")
        self.buttonGroup.addButton(self.y_kx)
        self.horizontalLayout.addWidget(self.y_kx)
        self.y_kx_b = QtWidgets.QRadioButton(self.layoutWidget)
        self.y_kx_b.setObjectName("y_kx_b")
        self.buttonGroup.addButton(self.y_kx_b)
        self.horizontalLayout.addWidget(self.y_kx_b)
        self.y_k_x = QtWidgets.QRadioButton(self.layoutWidget)
        self.y_k_x.setObjectName("y_k_x")
        self.buttonGroup.addButton(self.y_k_x)
        self.horizontalLayout.addWidget(self.y_k_x)
        self.y_x = QtWidgets.QRadioButton(self.layoutWidget)
        self.y_x.setObjectName("y_x")
        self.buttonGroup.addButton(self.y_x)
        self.horizontalLayout.addWidget(self.y_x)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.y_ax_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.y_ax_2.setObjectName("y_ax_2")
        self.buttonGroup.addButton(self.y_ax_2)
        self.horizontalLayout_2.addWidget(self.y_ax_2)
        self.y_ax_3 = QtWidgets.QRadioButton(self.layoutWidget)
        self.y_ax_3.setObjectName("y_ax_3")
        self.buttonGroup.addButton(self.y_ax_3)
        self.horizontalLayout_2.addWidget(self.y_ax_3)
        self.y_sqrt = QtWidgets.QRadioButton(self.layoutWidget)
        self.y_sqrt.setObjectName("y_sqrt")
        self.buttonGroup.addButton(self.y_sqrt)
        self.horizontalLayout_2.addWidget(self.y_sqrt)
        self.y_cube = QtWidgets.QRadioButton(self.layoutWidget)
        self.y_cube.setObjectName("y_cube")
        self.buttonGroup.addButton(self.y_cube)
        self.horizontalLayout_2.addWidget(self.y_cube)
        self.y_a_x = QtWidgets.QRadioButton(self.layoutWidget)
        self.y_a_x.setObjectName("y_a_x")
        self.buttonGroup.addButton(self.y_a_x)
        self.horizontalLayout_2.addWidget(self.y_a_x)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 220, 183, 35))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.first_var = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.first_var.setFont(font)
        self.first_var.setObjectName("first_var")
        self.horizontalLayout_4.addWidget(self.first_var)
        self.first_value = QtWidgets.QLineEdit(self.layoutWidget1)
        self.first_value.setObjectName("first_value")
        self.horizontalLayout_4.addWidget(self.first_value)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(230, 220, 182, 35))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.second_var = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.second_var.setFont(font)
        self.second_var.setObjectName("second_var")
        self.horizontalLayout_5.addWidget(self.second_var)
        self.second_value = QtWidgets.QLineEdit(self.layoutWidget2)
        self.second_value.setObjectName("second_value")
        self.horizontalLayout_5.addWidget(self.second_value)
        self.inf = QtWidgets.QLabel(self.centralwidget)
        self.inf.setGeometry(QtCore.QRect(500, 250, 291, 181))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.inf.setFont(font)
        self.inf.setWhatsThis("")
        self.inf.setAutoFillBackground(False)
        self.inf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inf.setText("")
        self.inf.setScaledContents(True)
        self.inf.setObjectName("inf")
        self.greet_text.raise_()
        self.graph.raise_()
        self.var_text.raise_()
        self.equal_text.raise_()
        self.inf_text.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.start.raise_()
        self.inf.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.greet_text.setText(_translate("MainWindow", "  Выберите формулу уравнения:"))
        self.start.setText(_translate("MainWindow", "Вычислить"))
        self.var_text.setText(_translate("MainWindow", "Введите значения переменной:"))
        self.equal_text.setText(_translate("MainWindow", "Выбрано уравнение: y = ..."))
        self.inf_text.setText(_translate("MainWindow", "Справка по уравнению:"))
        self.y_const.setText(_translate("MainWindow", "y = const"))
        self.y_kx.setText(_translate("MainWindow", "y = kx"))
        self.y_kx_b.setText(_translate("MainWindow", "y = kx + b"))
        self.y_k_x.setText(_translate("MainWindow", "y = k / x"))
        self.y_x.setText(_translate("MainWindow", "y = |x|"))
        self.y_ax_2.setText(_translate("MainWindow", "y = ax^2"))
        self.y_ax_3.setText(_translate("MainWindow", "y = ax^3"))
        self.y_sqrt.setText(_translate("MainWindow", "y = x^(1/2)"))
        self.y_cube.setText(_translate("MainWindow", "y = x^(1/3)"))
        self.y_a_x.setText(_translate("MainWindow", "y = a^x"))
        self.first_var.setText(_translate("MainWindow", "const ="))
        self.second_var.setText(_translate("MainWindow", "b ="))
from pyqtgraph import PlotWidget
