# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.text.setFont(font)
        self.text.setObjectName("text")
        self.a = QtWidgets.QLabel(self.centralwidget)
        self.a.setGeometry(QtCore.QRect(10, 60, 38, 24))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.a.setFont(font)
        self.a.setObjectName("a")
        self.b = QtWidgets.QLabel(self.centralwidget)
        self.b.setGeometry(QtCore.QRect(130, 60, 38, 24))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.b.setFont(font)
        self.b.setObjectName("b")
        self.c = QtWidgets.QLabel(self.centralwidget)
        self.c.setGeometry(QtCore.QRect(250, 60, 36, 24))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.c.setFont(font)
        self.c.setObjectName("c")
        self.input_a = QtWidgets.QLineEdit(self.centralwidget)
        self.input_a.setGeometry(QtCore.QRect(50, 60, 71, 31))
        self.input_a.setObjectName("input_a")
        self.input_b = QtWidgets.QLineEdit(self.centralwidget)
        self.input_b.setGeometry(QtCore.QRect(170, 60, 71, 31))
        self.input_b.setObjectName("input_b")
        self.input_c = QtWidgets.QLineEdit(self.centralwidget)
        self.input_c.setGeometry(QtCore.QRect(290, 60, 71, 31))
        self.input_c.setObjectName("input_c")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(495, 10, 291, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.first_eq = QtWidgets.QLabel(self.centralwidget)
        self.first_eq.setGeometry(QtCore.QRect(10, 120, 451, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.first_eq.setFont(font)
        self.first_eq.setObjectName("first_eq")
        self.b_let = QtWidgets.QLabel(self.centralwidget)
        self.b_let.setGeometry(QtCore.QRect(20, 130, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.b_let.setFont(font)
        self.b_let.setObjectName("b_let")
        self._b = QtWidgets.QLabel(self.centralwidget)
        self._b.setGeometry(QtCore.QRect(60, 100, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._b.setFont(font)
        self._b.setObjectName("_b")
        self.a_2 = QtWidgets.QLabel(self.centralwidget)
        self.a_2.setGeometry(QtCore.QRect(60, 120, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.a_2.setFont(font)
        self.a_2.setObjectName("a_2")
        self.__ = QtWidgets.QLabel(self.centralwidget)
        self.__.setGeometry(QtCore.QRect(60, 100, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.__.setFont(font)
        self.__.setObjectName("__")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(600, 500, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.ix2a = QtWidgets.QLabel(self.centralwidget)
        self.ix2a.setGeometry(QtCore.QRect(120, 120, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ix2a.setFont(font)
        self.ix2a.setText("")
        self.ix2a.setObjectName("ix2a")
        self.ix_b = QtWidgets.QLabel(self.centralwidget)
        self.ix_b.setGeometry(QtCore.QRect(120, 100, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ix_b.setFont(font)
        self.ix_b.setText("")
        self.ix_b.setObjectName("ix_b")
        self.ix__ = QtWidgets.QLabel(self.centralwidget)
        self.ix__.setGeometry(QtCore.QRect(120, 100, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ix__.setFont(font)
        self.ix__.setText("")
        self.ix__.setObjectName("ix__")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 370, 111, 61))
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text.setText(_translate("MainWindow", "Введите значения переменных:"))
        self.a.setText(_translate("MainWindow", "a = "))
        self.b.setText(_translate("MainWindow", "b = "))
        self.c.setText(_translate("MainWindow", "c = "))
        self.first_eq.setText(_translate("MainWindow", "x =     = ..."))
        self.b_let.setText(_translate("MainWindow", " в"))
        self._b.setText(_translate("MainWindow", "-b"))
        self.a_2.setText(_translate("MainWindow", "2a"))
        self.__.setText(_translate("MainWindow", "__"))
        self.start.setText(_translate("MainWindow", "Вычислить"))
from pyqtgraph import PlotWidget
